/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Ahorcado.java
 *
 * Created on 23-dic-2010, 0:24:28
 */

/**
 *
 * @author victor
 */
import java.awt.*;
import javax.swing.*;
import java.io.*;
public class Ahorcado extends javax.swing.JFrame {

    /** Creates new form Ahorcado */
    public Ahorcado() {
        initComponents();
        initComponents1();
    }
    //declaracion de todas las variablesa utilizar
static String aux[],nuevo="",plb="",com; String nuevo1="";
static boolean ban=false;char caracter;String auxplb="";
static int extra,cont=0,fon;
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jSeparator4 = new javax.swing.JSeparator();
        jMenu6 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ahorcado");
        setBackground(new java.awt.Color(64, 215, 64));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24));
        jLabel1.setForeground(new java.awt.Color(29, 130, 37));
        jLabel1.setText("Juego del Ahorcado");

        jLabel2.setFont(new java.awt.Font("Century Schoolbook L", 1, 18));
        jLabel2.setForeground(new java.awt.Color(139, 42, 42));
        jLabel2.setText("Inserta la letra que creeas");

        jTextField1.setEditable(false);
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Century Schoolbook L", 1, 18));
        jLabel3.setForeground(new java.awt.Color(139, 42, 42));
        jLabel3.setText("Palabra");

        jTextField2.setEditable(false);
        jTextField2.setToolTipText("Si! ya sabes la palabra ponla aqui y gana");

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("URW Gothic L", 1, 43)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(206, 210, 40));
        jTextField3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(9, 241, 11)));

        jButton1.setBackground(new java.awt.Color(80, 40, 226));
        jButton1.setForeground(new java.awt.Color(134, 39, 39));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ahorcado.gif"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INICIAR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 18), new java.awt.Color(128, 24, 24))); // NOI18N

        jMenuBar1.setBackground(new java.awt.Color(115, 30, 30));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 247, 20)));
        jMenuBar1.setForeground(new java.awt.Color(221, 240, 18));

        jMenu1.setText("Archivo");

        jMenu5.setText("Salir");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenu1.add(jMenu5);
        jMenu1.add(jSeparator4);

        jMenu6.setText("Agregar palabra");
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });
        jMenu1.add(jMenu6);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("?");

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/q.jpg"))); // NOI18N
        jMenu3.setText("Ayuda");
        jMenu3.add(jSeparator1);
        jMenu3.add(jSeparator2);

        jMenu2.add(jMenu3);
        jMenu2.add(jSeparator3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ac.png"))); // NOI18N
        jMenu4.setText("Acerca de..");
        jMenu2.add(jMenu4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(295, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(592, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(744, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(759, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(434, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
                .addContainerGap(639, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(jButton1)
                .addGap(80, 80, 80)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu5MouseClicked

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked
        // TODO add your handling code here:
          ban=true;
        extra=Integer.parseInt(JOptionPane.showInputDialog("cuantas palabras extras seran?"));
        aux=agrega(extra);
    }//GEN-LAST:event_jMenu6MouseClicked

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        int num;int num1=0;
        num=evt.getKeyCode();


             if(num==10)
        {


       //leo la letra que intrudujo el usuario
        com=jTextField1.getText();
//reinicio el valor de plb
       // plb="";
       String ban1="";int caso=1;
      // caracter=new char[nuevo.length()];

                caracter=com.charAt(0);

//char caracter=com.charAt(0);
                 //una pequeña comparacion para saber si existe la letra escrita
                 for(int i=0; i<nuevo.length();i++ )
                 {
                     if(nuevo.charAt(i)==caracter)
                     {num1++;
                     }
                 }
                if(num1==0)
                {fon++;repaint();//System.out.println(" a"+fon);
                 if(fon>3)
                 {
                     
                     fon=0;
                 }
                }
                //hasta aqui las comparaciones

nuevo1="";
for(int i=0; i<nuevo.length();i++)
{
    if(nuevo.charAt(i)==caracter)

  nuevo1+=caracter;

else
{
          nuevo1+=auxplb.charAt(i);
}
    
}
auxplb=nuevo1;

        //ban1+=nuevo1.charAt(i);
      
  jTextField1.setText(""); 
jTextField3.setText(""+nuevo1);
if(nuevo1.equalsIgnoreCase(nuevo))
{
JOptionPane.showMessageDialog(null,"Felicidades ganaste");
}

    }//GEN-LAST:event_jTextField1KeyPressed
    }
    //inicia eventos nuevos
     private void initComponents1() {
       jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
         jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
          jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });
            }
     //evento de la palabra completa
     private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {
            // TODO add your handling code here:
          int num;
        num=evt.getKeyCode();

String compara;
             if(num==10)
        { System.out.println("holaa ");
       compara=jTextField2.getText();
       if(compara.equalsIgnoreCase(nuevo))
       {
       JOptionPane.showMessageDialog(null,"Felicidades ganaste");
       jTextField3.setText(""+compara);
       jTextField1.setEditable(false);
       jTextField2.setEditable(false);
       jTextField2.setText("");
       jTextField1.setText("");
       }
       else
       {
       JOptionPane.showMessageDialog(null,"GAME OVER");
        jTextField3.setText(""+nuevo);
       jTextField1.setEditable(false);
       jTextField2.setEditable(false);
       jTextField2.setText("");
       jTextField1.setText("");
       repaint();
       fon=3;
       }
        }
        }

     //hasta aqui los eventos nuevos
//inicio evento del menu
      private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {
            // TODO add your handling code here:
           NewDialog b=new NewDialog(this,true);
        b.pack();
        b.setSize(517,488);
        b.setVisible(true);
        }//termina evento del menu
      //inicia evento de otro menu
       private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {
 NewDialog1 a=new NewDialog1((JFrame)this,true);
 a.pack();

        a.setSize(410,268);
        a.setLocation(300,320);
        a.setVisible(true);        // TODO add your handling code here:
    }

      //inicia evento al dar enter
private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
    jTextField1.setEditable(true);
    jTextField2.setEditable(true);
    if(ban==false)
      {
      aux=agrega(0);
      }
plb="";
        java.util.Random r=new java.util.Random();
        int ram;
        ram=r.nextInt(aux.length);
        aux[ram].concat(nuevo);
        
       // System.out.println(aux[ram]+""+ram);

        for(int i=0; i<aux[ram].length(); i++)
        {//pongo _ para decir que ahi va una letra
        plb+="_";
        }
       
       nuevo=aux[ram];
       // System.out.println(""+plb+aux[ram].length()+"  "+nuevo);

        auxplb=plb;
  jTextField3.setText(""+plb);
  JOptionPane.showMessageDialog(null,"Numero de letras "+nuevo.length());
   repaint();
        }
    
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ahorcado().setVisible(true);
            }
        });
        
               }
 public void paint(Graphics g)
{//se dibuja al ahorcado
    paintComponents(g);
  //g.drawImage(Imagenes.cargaImagen("logo2.gif"),mx,my,this);
  
    g.drawImage(Imagenes.cargaImagen("7.png"),500,90,this);
      g.drawImage(Imagenes.cargaImagen("VM2.jpg"),750,50,this);
 
    switch(fon)
    {

        case 1:
 g.drawImage(Imagenes.cargaImagen("2.png"),570,370,this);
g.drawImage(Imagenes.cargaImagen("1.png"),650,370,this);

         break;
        case 2:
 g.drawImage(Imagenes.cargaImagen("2.png"),570,370,this);
g.drawImage(Imagenes.cargaImagen("1.png"),650,370,this);
   g.drawImage(Imagenes.cargaImagen("3.png"),600,230,this);
    g.drawImage(Imagenes.cargaImagen("5.png"),660,260,this);
g.drawImage(Imagenes.cargaImagen("4.png"),570,260,this);
            break;
        case 3:
          
g.drawImage(Imagenes.cargaImagen("2.png"),570,370,this);
g.drawImage(Imagenes.cargaImagen("1.png"),650,370,this);
g.drawImage(Imagenes.cargaImagen("3.png"),600,230,this);
g.drawImage(Imagenes.cargaImagen("4.png"),570,260,this);
g.drawImage(Imagenes.cargaImagen("5.png"),660,260,this);
g.drawImage(Imagenes.cargaImagen("6.png"),620,190,this);
//g.drawImage(Imagenes.cargaImagen("7.png"),500,90,this);
JOptionPane.showMessageDialog(null,"GAME OVER");
fon=0;
break;
    }
}
 static String [] agrega(int nn)
    {
        //arreglo donde iran guardada todas las palabras
        int n=10;
        n+=nn;
    String palabras []=new String [n];

        palabras[0]="casa";
        palabras[1]="perros";
        palabras[2]="arboles";
        palabras[3]="mexico";
        palabras[4]="argentina";
        palabras[5]="europa";
        palabras[6]="caballo";
                palabras[7]="aeropuerto";
                palabras[8]="playa";
                palabras[9]="escuela";
               if((palabras.length)>=10)
               {
                   for(int i=10; i<palabras.length; i++)
                   {
                     palabras[i]=JOptionPane.showInputDialog("inserta la nueva palabra");
                   }
               }




    //regresa el mismo arreglo creado arriba pero lleno
    return palabras;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private static javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

}
