/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewDialog.java
 *
 * Created on 25-dic-2010, 23:18:31
 */

/**
 *
 * @author victor
 */
import java.awt.*;
public class NewDialog extends java.awt.Dialog {

    /** Creates new form NewDialog */
    public NewDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new Panel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    /*public void paint(Graphics g)
    {
    super.paint(g);
    g.drawImage(Imagenes.cargaImagen("ayuda.jpg"),0,0,this);
    g.setColor(new Color(100,0,255));
     setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
    g.drawString("Paso 1:Iniciar los valores con los que comenzara el metodo  ", 10, 90);
    g.drawString("el programa por defecto comenzara con X=0, Y=0, Z=0", 10,110);
    g.drawString("Paso 2: Inserta Es como error aproximado a alcanzar", 10, 170);
       g.drawString("Paso 3: Inserta la ecuacion de la forma AX+BY+CZ=D", 10, 230);
          g.drawString("Paso 4: Click en el icono de la calculadora y listo", 10, 290);
              g.drawString("resultado en la tabla", 10, 310);

               g.setColor(Color.RED);
                g.drawString("nota :*puede introducir las ecuaciones en la forma que quiera", 10, 390);
                 g.drawString("el programa se encargara de ordenarlo, respete los signos", 10, 410);
                 g.drawString("el + es solo para comservarlos", 10,430);



    }*/

    /**
    * @param args the command line arguments
    */
/*
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewDialog dialog = new NewDialog(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Panel panel1;
    // End of variables declaration//GEN-END:variables

}
